/* pathfinder.js — slide tiles into the open space until the two amber
   terminals connect. This mirrors the real HireVue Pathfinder mechanic
   (a 15-puzzle-style slide, confirmed against multiple independent
   candidate/prep-vendor descriptions) -- an earlier version of this file
   rotated tiles in place instead, which is a different puzzle genre
   (Pipes/NetWalk) that HireVue's actual game does not use.

   Generation is solvable by construction: carve a random path with DFS,
   lay the correct connectors along it in their FINAL orientation (nothing
   rotates now, only position changes), then scramble by replaying real
   slide moves from that solved state -- every scrambled position is
   therefore reachable back to solved, the same guarantee rotation gave
   before, just via moves instead of spins.

   Real Pathfinder runs a single 5-minute clock with no per-puzzle timer,
   and lets you skip a puzzle at the cost of a level rather than forcing
   you to solve it. Both are reproduced here instead of the old per-level
   countdown.

   Connection directions are indexed 0=N 1=E 2=S 3=W throughout. */

(function () {
  var DR = [-1, 0, 1, 0];
  var DC = [0, 1, 0, -1];
  var PF_TIME = 300;

  /* Every rotation of straight/corner/T-junction. Decoys don't rotate once
     placed -- there's no rotation mechanic anymore -- so the full set has
     to be enumerated up front instead of generated by spinning one shape. */
  var DECOY_SHAPES = [
    [1, 0, 1, 0], [0, 1, 0, 1],
    [1, 1, 0, 0], [0, 1, 1, 0], [0, 0, 1, 1], [1, 0, 0, 1],
    [1, 1, 0, 1], [1, 1, 1, 0], [0, 1, 1, 1], [1, 0, 1, 1]
  ];

  function key(p) { return p.r + ',' + p.c; }

  function makeSolvedGrid(n) {
    var cells = [], r, c;
    for (r = 0; r < n; r++) {
      cells.push([]);
      for (c = 0; c < n; c++) cells[r].push({ conn: [0, 0, 0, 0], path: false });
    }

    var start = { r: AP.ri(0, n - 1), c: 0 };
    var end = { r: AP.ri(0, n - 1), c: n - 1 };
    var seen = {}, found = null;

    function dfs(p, acc) {
      if (found) return;
      if (p.r === end.r && p.c === end.c) {
        if (acc.length >= n + 1) found = acc.slice();
        return;
      }
      var order = AP.shuffle([0, 1, 2, 3]);
      for (var i = 0; i < 4; i++) {
        var d = order[i], nr = p.r + DR[d], nc = p.c + DC[d];
        if (nr < 0 || nc < 0 || nr >= n || nc >= n) continue;
        var np = { r: nr, c: nc };
        if (seen[key(np)]) continue;
        seen[key(np)] = 1;
        acc.push(np);
        dfs(np, acc);
        if (found) return;
        acc.pop();
        delete seen[key(np)];
      }
    }

    seen[key(start)] = 1;
    dfs(start, [start]);
    if (!found) found = [start, end];

    for (var i = 0; i < found.length - 1; i++) {
      var a = found[i], b = found[i + 1];
      for (var d = 0; d < 4; d++) {
        if (a.r + DR[d] === b.r && a.c + DC[d] === b.c) {
          cells[a.r][a.c].conn[d] = 1;
          cells[b.r][b.c].conn[(d + 2) % 4] = 1;
        }
      }
    }
    found.forEach(function (p) { cells[p.r][p.c].path = true; });

    for (r = 0; r < n; r++) {
      for (c = 0; c < n; c++) {
        if (!cells[r][c].path) cells[r][c].conn = AP.pick(DECOY_SHAPES).slice();
      }
    }

    var nonPath = [];
    for (r = 0; r < n; r++) {
      for (c = 0; c < n; c++) if (!cells[r][c].path) nonPath.push({ r: r, c: c });
    }
    var emptyPos = nonPath.length ? AP.pick(nonPath) : { r: 0, c: 0 };

    return { n: n, cells: cells, start: start, end: end, empty: emptyPos };
  }

  function neighbors(p, n) {
    var out = [];
    for (var d = 0; d < 4; d++) {
      var nr = p.r + DR[d], nc = p.c + DC[d];
      if (nr >= 0 && nc >= 0 && nr < n && nc < n) out.push({ r: nr, c: nc });
    }
    return out;
  }

  /* Scramble via real slides only, so every reachable state is solvable by
     definition -- same guarantee the old rotate-by-construction had. Avoids
     immediately undoing the previous move so it doesn't waste half its
     budget oscillating between two states. */
  function scramble(g, moves) {
    var last = null;
    for (var i = 0; i < moves; i++) {
      var all = neighbors(g.empty, g.n);
      var opts = all.filter(function (p) { return !last || p.r !== last.r || p.c !== last.c; });
      var pick = AP.pick(opts.length ? opts : all);
      var tmp = g.cells[g.empty.r][g.empty.c];
      g.cells[g.empty.r][g.empty.c] = g.cells[pick.r][pick.c];
      g.cells[pick.r][pick.c] = tmp;
      last = g.empty;
      g.empty = pick;
    }
  }

  function isAdjacent(a, b) { return (Math.abs(a.r - b.r) + Math.abs(a.c - b.c)) === 1; }

  /* Flood fill from the start across mutually-open edges. */
  function reachable(g) {
    var seen = {}, queue = [g.start];
    seen[key(g.start)] = 1;
    while (queue.length) {
      var p = queue.shift(), cell = g.cells[p.r][p.c];
      for (var d = 0; d < 4; d++) {
        if (!cell.conn[d]) continue;
        var nr = p.r + DR[d], nc = p.c + DC[d];
        if (nr < 0 || nc < 0 || nr >= g.n || nc >= g.n) continue;
        if (!g.cells[nr][nc].conn[(d + 2) % 4]) continue;
        var k = nr + ',' + nc;
        if (seen[k]) continue;
        seen[k] = 1;
        queue.push({ r: nr, c: nc });
      }
    }
    return seen;
  }

  function pipeSVG(conn, lit, terminal) {
    var col = lit ? '#E8EEF4' : '#BBDEFB';
    var ends = [[30, 0], [60, 30], [30, 60], [0, 30]];
    var s = '<svg viewBox="0 0 60 60">';
    for (var d = 0; d < 4; d++) {
      if (conn[d]) {
        s += '<line x1="30" y1="30" x2="' + ends[d][0] + '" y2="' + ends[d][1] +
          '" stroke="' + col + '" stroke-width="14"/>';
      }
    }
    if (terminal) s += '<circle cx="30" cy="30" r="9" fill="#F5A623"/>';
    return s + '</svg>';
  }

  function draw() {
    AP.el(AP.board(AP.chrome(true, false) +
      '<div class="field f-path"><div class="pgrid" id="pg" style="grid-template-columns:repeat(' +
      AP.S.g.n + ',1fr)"></div>' +
      '<button class="cta" id="pfSkip">Skip this one</button></div>'));
    AP.wire();
    paint();
    AP.$('pfSkip').addEventListener('click', function () {
      if (AP.S.locked) return;
      AP.S.level = Math.max(1, AP.S.level - 1);
      next();
    });
  }

  function paint() {
    var g = AP.S.g, lit = reachable(g), pg = AP.$('pg');
    if (!pg) return;
    pg.innerHTML = '';

    for (var r = 0; r < g.n; r++) {
      for (var c = 0; c < g.n; c++) {
        (function (r, c) {
          var isEmpty = g.empty.r === r && g.empty.c === c;
          var cell = g.cells[r][c];
          var on = !isEmpty && !!lit[key({ r: r, c: c })];
          var terminal = !isEmpty &&
            ((r === g.start.r && c === g.start.c) || (r === g.end.r && c === g.end.c));
          var slidable = !isEmpty && isAdjacent({ r: r, c: c }, g.empty);

          var b = document.createElement('button');
          b.className = 'pcell' + (on ? ' lit' : '') + (isEmpty ? ' empty' : '') +
            (slidable ? ' slidable' : '');
          b.innerHTML = isEmpty ? '' : pipeSVG(cell.conn, on, terminal);
          b.addEventListener('click', function () {
            if (AP.S.locked || isEmpty || !slidable) return;
            var tmp = g.cells[g.empty.r][g.empty.c];
            g.cells[g.empty.r][g.empty.c] = cell;
            g.cells[r][c] = tmp;
            g.empty = { r: r, c: c };
            AP.S.moves++;
            paint();
            if (reachable(g)[key(g.end)]) {
              AP.S.locked = true;
              AP.S.score++;
              AP.S.level++;
              AP.misc = setTimeout(next, 460);
            }
          });
          pg.appendChild(b);
        })(r, c);
      }
    }
  }

  function next() {
    var S = AP.S;
    if (S.left <= 0) return;
    var n = S.level < 4 ? 3 : (S.level < 9 ? 4 : 5);
    S.g = makeSolvedGrid(n);
    scramble(S.g, n * n * 3);
    S.locked = false;
    draw();
  }

  function finish() {
    var S = AP.S;
    AP.results('pf', S.score,
      [['Solved', S.score], ['Level', S.level], ['Moves', S.moves]],
      '<b>Strategy:</b> work the empty slot toward where the amber terminals still need to connect, one slide ' +
      'at a time, like a 15-puzzle &mdash; plan two or three moves ahead instead of sliding whatever happens ' +
      'to be adjacent. Skip a puzzle that has gone sideways rather than fighting it: it costs a level, not ' +
      'your remaining time, since there is no per-puzzle clock, only one 5-minute session timer.',
      start);
  }

  function start() {
    AP.stopAll();
    AP.S = { score: 0, level: 1, locked: false, moves: 0, left: PF_TIME };
    next();
    AP.gameClock(finish, PF_TIME);
  }

  AP.games.pf = { start: start };
})();
